-- Roll back Ripple deterministic data foundation. Destructive: review before use.
USE DATABASE RIPPLE;

DROP TABLE IF EXISTS EVAL.BENCHMARK_METRIC;
DROP TABLE IF EXISTS EVAL.BENCHMARK_LABEL;
DROP TABLE IF EXISTS OPS.COST_EVENT;
DROP TABLE IF EXISTS OPS.CAPABILITY_RECORD;
DROP TABLE IF EXISTS OPS.SCHEMA_MIGRATION;
DROP TABLE IF EXISTS OPS.AUDIT_EVENT;
DROP TABLE IF EXISTS APP.VERIFICATION_RESULT;
DROP TABLE IF EXISTS APP.MUTATION_REPLAY;
DROP TABLE IF EXISTS APP.REVIEW_DECISION;
DROP TABLE IF EXISTS APP.PATCH_PROPOSAL;
DROP TABLE IF EXISTS PIPELINE.AI_RUN;
DROP TABLE IF EXISTS PIPELINE.IMPACT_FINDING;
DROP TABLE IF EXISTS PIPELINE.CHANGE_ATOM;
DROP TABLE IF EXISTS PIPELINE.SECTION_DIFF;
DROP TABLE IF EXISTS PIPELINE.PIPELINE_STAGE;
DROP TABLE IF EXISTS PIPELINE.PIPELINE_RUN;
DROP TABLE IF EXISTS CORE.EXPLICIT_DEPENDENCY;
DROP TABLE IF EXISTS CORE.ASSET_VERSION;
DROP TABLE IF EXISTS CORE.KNOWLEDGE_ASSET;
DROP TABLE IF EXISTS CORE.SOURCE_SECTION;
DROP TABLE IF EXISTS CORE.SOURCE_SNAPSHOT;
DROP TABLE IF EXISTS CORE.SOURCE;
DROP TABLE IF EXISTS RAW.FIXTURE_MANIFEST;
DROP STAGE IF EXISTS RAW.CODE_STAGE;
DROP STAGE IF EXISTS RAW.FIXTURE_STAGE;
