-- Remove bounded task-graph state. Apply only after procedure/task rollback 004.
USE DATABASE RIPPLE;

DROP TABLE IF EXISTS OPS.TASK_PROOF;
DROP TABLE IF EXISTS OPS.CHAOS_CONTROL;
DROP TABLE IF EXISTS OPS.AI_DAILY_ADMISSION;
DROP TABLE IF EXISTS PIPELINE.CANDIDATE_RETRIEVAL;
DROP STREAM IF EXISTS PIPELINE.RUN_TRIGGER_STREAM;
DROP TABLE IF EXISTS PIPELINE.TRIGGER_CONSUMED;
DROP TABLE IF EXISTS PIPELINE.RUN_TRIGGER;
ALTER TABLE PIPELINE.PIPELINE_RUN DROP COLUMN IF EXISTS run_context;
