-- Suspend and remove the task graph before removing its state tables.
USE DATABASE RIPPLE;

ALTER TASK IF EXISTS PIPELINE.ROOT_TASK SUSPEND;
DROP TASK IF EXISTS PIPELINE.FINALIZE_TASK;
DROP TASK IF EXISTS PIPELINE.ROOT_TASK;
DROP PROCEDURE IF EXISTS PIPELINE.RUN_PENDING();
DROP PROCEDURE IF EXISTS API.RUN_PIPELINE(STRING);
DROP PROCEDURE IF EXISTS API.START_ANALYSIS(STRING, STRING, STRING, STRING);
