-- Remove Phase 4 SQL/Scripting patch mutation boundaries.
USE DATABASE RIPPLE;

DROP PROCEDURE IF EXISTS API.APPLY_PATCH(
    STRING,
    NUMBER,
    NUMBER,
    STRING,
    STRING,
    STRING,
    STRING,
    STRING
);
DROP PROCEDURE IF EXISTS API.REJECT_PATCH(
    STRING,
    NUMBER,
    NUMBER,
    STRING,
    STRING,
    STRING
);
DROP PROCEDURE IF EXISTS API.REVISE_PATCH(
    STRING,
    NUMBER,
    NUMBER,
    STRING,
    STRING,
    STRING,
    STRING
);
DROP PROCEDURE IF EXISTS OPS.APPEND_AUDIT(
    STRING,
    STRING,
    STRING,
    STRING,
    STRING,
    VARIANT
);
