-- Remove the sanitized application read models.
USE DATABASE RIPPLE;

DROP VIEW IF EXISTS API.PROOF_V;
DROP VIEW IF EXISTS API.PATCH_DETAIL_V;
DROP VIEW IF EXISTS API.RUN_FINDING_V;
DROP VIEW IF EXISTS API.RUN_GRAPH_V;
DROP VIEW IF EXISTS API.RUN_STAGE_V;
DROP VIEW IF EXISTS API.DASHBOARD_V;
DROP VIEW IF EXISTS API.RUN_SUMMARY_V;
