-- Remove the optional live-monitor extension and its stored state.
USE DATABASE RIPPLE;

DROP VIEW IF EXISTS API.RUN_PROVENANCE_V;
DROP VIEW IF EXISTS API.MONITOR_NOTIFICATION_V;
DROP VIEW IF EXISTS API.MONITOR_DUE_V;
DROP VIEW IF EXISTS API.MONITOR_V;
DROP PROCEDURE IF EXISTS API.MARK_MONITOR_NOTIFICATION(STRING, STRING);
DROP PROCEDURE IF EXISTS API.SET_MONITOR_ENABLED(STRING, BOOLEAN, NUMBER);
DROP PROCEDURE IF EXISTS API.INGEST_MONITOR(STRING, STRING, STRING, STRING);
DROP TABLE IF EXISTS OPS.MONITOR_CHECK;
DROP TABLE IF EXISTS APP.SOURCE_MONITOR;
DROP TABLE IF EXISTS RAW.LIVE_SOURCE_CONTENT;
