-- Fresh-account bootstrap for Ripple account objects.
-- Run with ACCOUNTADMIN and Snowflake CLI STANDARD templating.
-- Required variables: owner_user, app_rsa_public_key, admin_rsa_public_key.

USE SECONDARY ROLES NONE;
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RIPPLE_ADMIN_ROLE
    COMMENT = 'Owns Ripple project objects; never used by the running application';
CREATE ROLE IF NOT EXISTS RIPPLE_MIGRATOR_ROLE
    COMMENT = 'Applies reviewed immutable Ripple migrations';
CREATE ROLE IF NOT EXISTS RIPPLE_PIPELINE_ROLE
    COMMENT = 'Runs bounded Ripple pipeline procedures and tasks';
CREATE ROLE IF NOT EXISTS RIPPLE_APP_ROLE
    COMMENT = 'Executes approved Ripple API procedures and reads approved API views';
CREATE ROLE IF NOT EXISTS RIPPLE_READONLY_ROLE
    COMMENT = 'Reads sanitized Ripple diagnostics and API views';

GRANT ROLE RIPPLE_MIGRATOR_ROLE TO ROLE RIPPLE_ADMIN_ROLE;
GRANT ROLE RIPPLE_PIPELINE_ROLE TO ROLE RIPPLE_ADMIN_ROLE;
GRANT ROLE RIPPLE_APP_ROLE TO ROLE RIPPLE_ADMIN_ROLE;
GRANT ROLE RIPPLE_READONLY_ROLE TO ROLE RIPPLE_ADMIN_ROLE;
GRANT ROLE RIPPLE_ADMIN_ROLE TO ROLE SYSADMIN;
GRANT ROLE RIPPLE_ADMIN_ROLE TO USER IDENTIFIER('<% owner_user %>');

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE RIPPLE_ADMIN_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE RIPPLE_PIPELINE_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE RIPPLE_ADMIN_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE RIPPLE_PIPELINE_ROLE;

CREATE RESOURCE MONITOR IF NOT EXISTS RIPPLE_BUILD_MONITOR
    WITH
        CREDIT_QUOTA = 5
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 80 PERCENT DO NOTIFY
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS RIPPLE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Zero-additional-spend Ripple development and demo warehouse';
ALTER WAREHOUSE RIPPLE_WH SET RESOURCE_MONITOR = RIPPLE_BUILD_MONITOR;
GRANT OWNERSHIP ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_ADMIN_ROLE COPY CURRENT GRANTS;

CREATE DATABASE IF NOT EXISTS RIPPLE
    COMMENT = 'Evidence-backed downstream change detection and repair';
GRANT OWNERSHIP ON DATABASE RIPPLE TO ROLE RIPPLE_ADMIN_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS RIPPLE_APP_USER
    TYPE = SERVICE
    DEFAULT_ROLE = RIPPLE_APP_ROLE
    DEFAULT_WAREHOUSE = RIPPLE_WH
    DEFAULT_NAMESPACE = 'RIPPLE.API'
    RSA_PUBLIC_KEY = '<% app_rsa_public_key %>'
    COMMENT = 'Key-pair-only service identity for the Ripple edge API';
CREATE USER IF NOT EXISTS RIPPLE_AUTOMATION_USER
    TYPE = SERVICE
    DEFAULT_ROLE = RIPPLE_ADMIN_ROLE
    DEFAULT_WAREHOUSE = RIPPLE_WH
    DEFAULT_NAMESPACE = 'RIPPLE.OPS'
    RSA_PUBLIC_KEY = '<% admin_rsa_public_key %>'
    COMMENT = 'Key-pair-only project-scoped migration identity';

GRANT ROLE RIPPLE_APP_ROLE TO USER RIPPLE_APP_USER;
GRANT ROLE RIPPLE_ADMIN_ROLE TO USER RIPPLE_AUTOMATION_USER;

GRANT USAGE ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_MIGRATOR_ROLE;
GRANT USAGE ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_APP_ROLE;
GRANT USAGE ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_READONLY_ROLE;

USE ROLE RIPPLE_ADMIN_ROLE;
CREATE SCHEMA IF NOT EXISTS RIPPLE.API;
CREATE OR REPLACE PROCEDURE RIPPLE.API.HEALTH()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    RETURN OBJECT_CONSTRUCT('status', 'ok', 'service', 'ripple-snowflake-api');
END;
$$;

GRANT USAGE ON DATABASE RIPPLE TO ROLE RIPPLE_APP_ROLE;
GRANT USAGE ON SCHEMA RIPPLE.API TO ROLE RIPPLE_APP_ROLE;
GRANT USAGE ON PROCEDURE RIPPLE.API.HEALTH() TO ROLE RIPPLE_APP_ROLE;
