-- Ripple capability-preflight resources.
-- REVIEWED EXECUTION ONLY: this file creates Snowflake account objects.
-- Invoke with Snowflake CLI STANDARD templating and a locally derived RSA public key.

USE ROLE ACCOUNTADMIN;

SET ripple_owner_user = CURRENT_USER();

CREATE ROLE IF NOT EXISTS RIPPLE_ADMIN_ROLE
  COMMENT = 'Owns Ripple project objects; never used by the running application';

CREATE ROLE IF NOT EXISTS RIPPLE_APP_ROLE
  COMMENT = 'Executes only approved Ripple API procedures and reads approved API views';

GRANT ROLE RIPPLE_APP_ROLE TO ROLE RIPPLE_ADMIN_ROLE;
GRANT ROLE RIPPLE_ADMIN_ROLE TO USER IDENTIFIER($ripple_owner_user);

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE RIPPLE_ADMIN_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE RIPPLE_ADMIN_ROLE;

CREATE RESOURCE MONITOR IF NOT EXISTS RIPPLE_BUILD_MONITOR
  WITH
    CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
      ON 80 PERCENT DO NOTIFY
      ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS RIPPLE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Zero-additional-spend Ripple development and demo warehouse';

ALTER WAREHOUSE RIPPLE_WH SET RESOURCE_MONITOR = RIPPLE_BUILD_MONITOR;
GRANT OWNERSHIP ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_ADMIN_ROLE COPY CURRENT GRANTS;

CREATE DATABASE IF NOT EXISTS RIPPLE
  COMMENT = 'Evidence-backed downstream change detection and repair';

GRANT OWNERSHIP ON DATABASE RIPPLE TO ROLE RIPPLE_ADMIN_ROLE COPY CURRENT GRANTS;

CREATE USER IF NOT EXISTS RIPPLE_APP_USER
  TYPE = SERVICE
  DEFAULT_ROLE = RIPPLE_APP_ROLE
  DEFAULT_WAREHOUSE = RIPPLE_WH
  DEFAULT_NAMESPACE = 'RIPPLE.API'
  RSA_PUBLIC_KEY = '<% rsa_public_key %>'
  COMMENT = 'Key-pair-only service identity for the Ripple edge API';

ALTER USER RIPPLE_APP_USER SET
  TYPE = SERVICE
  DEFAULT_ROLE = RIPPLE_APP_ROLE
  DEFAULT_WAREHOUSE = RIPPLE_WH
  DEFAULT_NAMESPACE = 'RIPPLE.API'
  RSA_PUBLIC_KEY = '<% rsa_public_key %>';

GRANT ROLE RIPPLE_APP_ROLE TO USER RIPPLE_APP_USER;

USE ROLE RIPPLE_ADMIN_ROLE;
USE WAREHOUSE RIPPLE_WH;

CREATE SCHEMA IF NOT EXISTS RIPPLE.PREFLIGHT
  COMMENT = 'Disposable capability probes; removed after fallback decisions freeze';

CREATE SCHEMA IF NOT EXISTS RIPPLE.API
  COMMENT = 'Fixed owner-executed procedures and read-only views exposed to RIPPLE_APP_ROLE';

CREATE OR REPLACE PROCEDURE RIPPLE.API.HEALTH()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
  RETURN OBJECT_CONSTRUCT(
    'status', 'ok',
    'service', 'ripple-snowflake-api'
  );
END;
$$;

GRANT USAGE ON WAREHOUSE RIPPLE_WH TO ROLE RIPPLE_APP_ROLE;
GRANT USAGE ON DATABASE RIPPLE TO ROLE RIPPLE_APP_ROLE;
GRANT USAGE ON SCHEMA RIPPLE.API TO ROLE RIPPLE_APP_ROLE;
GRANT USAGE ON PROCEDURE RIPPLE.API.HEALTH() TO ROLE RIPPLE_APP_ROLE;

USE ROLE ACCOUNTADMIN;

SHOW GRANTS TO ROLE RIPPLE_APP_ROLE;
SHOW GRANTS TO USER RIPPLE_APP_USER;
SHOW WAREHOUSES LIKE 'RIPPLE_WH';
SHOW RESOURCE MONITORS LIKE 'RIPPLE_BUILD_MONITOR';
