-- DESTRUCTIVE fresh-install teardown. Review the rollback runbook before execution.
USE SECONDARY ROLES NONE;
USE ROLE ACCOUNTADMIN;

ALTER TASK IF EXISTS RIPPLE.PIPELINE.ROOT_TASK SUSPEND;
DROP USER IF EXISTS RIPPLE_APP_USER;
DROP USER IF EXISTS RIPPLE_AUTOMATION_USER;
DROP DATABASE IF EXISTS RIPPLE;
DROP WAREHOUSE IF EXISTS RIPPLE_WH;
DROP RESOURCE MONITOR IF EXISTS RIPPLE_BUILD_MONITOR;
DROP ROLE IF EXISTS RIPPLE_READONLY_ROLE;
DROP ROLE IF EXISTS RIPPLE_APP_ROLE;
DROP ROLE IF EXISTS RIPPLE_PIPELINE_ROLE;
DROP ROLE IF EXISTS RIPPLE_MIGRATOR_ROLE;
DROP ROLE IF EXISTS RIPPLE_ADMIN_ROLE;
