-- Bounded task-graph, retrieval, admission, and retry state.
USE DATABASE RIPPLE;

ALTER TABLE PIPELINE.PIPELINE_RUN ADD COLUMN IF NOT EXISTS run_context VARIANT;

CREATE TABLE IF NOT EXISTS PIPELINE.RUN_TRIGGER (
    trigger_id STRING NOT NULL PRIMARY KEY NOT ENFORCED,
    run_id STRING NOT NULL,
    created_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PIPELINE.TRIGGER_CONSUMED (
    trigger_id STRING NOT NULL,
    run_id STRING NOT NULL,
    stream_action STRING NOT NULL,
    stream_is_update BOOLEAN NOT NULL,
    consumed_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE STREAM IF NOT EXISTS PIPELINE.RUN_TRIGGER_STREAM
ON TABLE PIPELINE.RUN_TRIGGER
APPEND_ONLY = TRUE;

CREATE TABLE IF NOT EXISTS PIPELINE.CANDIDATE_RETRIEVAL (
    candidate_id STRING NOT NULL PRIMARY KEY NOT ENFORCED,
    run_id STRING NOT NULL,
    change_atom_id STRING NOT NULL,
    asset_id STRING NOT NULL,
    asset_version_id STRING NOT NULL,
    retrieval_basis STRING NOT NULL CHECK (
        retrieval_basis IN ('EXPLICIT_DEPENDENCY', 'EXACT_TOKEN', 'LEXICAL')
    ),
    retrieval_score FLOAT NOT NULL,
    created_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPS.AI_DAILY_ADMISSION (
    admission_id STRING NOT NULL PRIMARY KEY NOT ENFORCED,
    usage_date DATE NOT NULL,
    run_id STRING NOT NULL,
    stage_name STRING NOT NULL,
    estimated_credits FLOAT NOT NULL CHECK (estimated_credits >= 0),
    status STRING NOT NULL CHECK (status IN ('ADMITTED', 'REJECTED')),
    created_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPS.CHAOS_CONTROL (
    control_id STRING NOT NULL PRIMARY KEY NOT ENFORCED,
    run_id STRING NOT NULL,
    stage_name STRING NOT NULL,
    fail_once BOOLEAN NOT NULL,
    consumed_at TIMESTAMP_TZ,
    created_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPS.TASK_PROOF (
    proof_id STRING NOT NULL PRIMARY KEY NOT ENFORCED,
    run_id STRING NOT NULL,
    run_status STRING NOT NULL,
    recorded_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
